// client/app/home/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Router } from '@angular/router';
import { EnvService } from 'client/app/shared/services/env.service';
import en from 'client/app/shared/language/en';
import { ApiAuthService } from 'client/app/shared/services/api/api-auth.service';
import { CookiesService } from 'client/app/shared/services/cookie.service';
import { HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DataResponse } from 'client/app/shared/types/response';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  l = en
  env: any

  name: string = ''
  password: string = ''

  private getAuth$!: Observable<HttpResponse<DataResponse<{ jwt: string }>>>

  constructor(private router: Router, private title: Title, private envService: EnvService, private apiAuthService: ApiAuthService, private cookiesService: CookiesService) { }

  async ngOnInit() {

    this.envService.get().subscribe({ next: (env) => { this.l = env.language; this.env = env; } })

    this.title.setTitle(this.l.auth.login + ' • ' + this.env.name + ' AdminTool')

    if (this.cookiesService.getCookie('JWT')) {
      this.apiAuthService.getVerify().subscribe({
        next: (res) => {
          this.router.navigate(['/dashboard'])
        }
      })
    }

  }

  async onSubmit() {

    document.querySelector<HTMLElement>('app-loading-splash#login-loading-splash')!.style.display = 'block'
    this.getAuth$ = this.apiAuthService.getAuth(this.name + '', this.password + '')
    this.getAuth$.subscribe(
      {
        next: async (res) => {
          this.cookiesService.setCookie({
            name: 'JWT',
            value: res.body?.data?.jwt + '',
            expireDays: 30,
          })
          this.router.navigate(['/dashboard'])
        },
        error: (err) => {
          document.querySelector<HTMLElement>('app-loading-splash#login-loading-splash')!.style.display = 'none'
        }
      }
    )

  }

}

<form (ngSubmit)="onSubmit()">
  <app-loading-splash [transparent]="true" id="login-loading-splash"></app-loading-splash>
  <h2 [innerHTML]="l.auth.login | html"></h2>
  <p>{{ env.name }} AdminTool</p>
  <input type="text" [placeholder]="l.main.username" [(ngModel)]="name" name="name">
  <input type="password" [placeholder]="l.main.password" [(ngModel)]="password" name="password">
  <button class="primary" [innerHTML]="l.auth.login| html"></button>
  <p class="center">
    <a class="small-link" routerLink="/register" [innerHTML]="l.auth.createAccount | html"></a>
  </p>
</form>

// client/src/routes/login/+page.svelte
<script lang="ts">
  // import type { PageData } from './$types';
  import '$assets/scss/login.scss'
  import LoadingSplash from '$components/LoadingSplash.svelte'
  import { env$ } from '$services/store'
  import ApiAuthService from '$services/api/api-auth.service'
  import CookiesService from '$services/cookies.service'
  import type { Env } from '$models/data/env.model'
  import type en from '$assets/language/en'
  import { goto } from '$app/navigation'
  import type { PageData } from './$types'

  export let data: PageData

  if (data.to !== '') {
    goto(data.to)
  }
  
  const apiAuth = new ApiAuthService()
  const cookies = new CookiesService()

  let env!: Env
  let l: typeof en | typeof en

  let name: string = ''
  let password = ''
  let splash: boolean = false

  env$.subscribe((value) => {
    if (value && typeof value.language !== 'string' && typeof value.language !== 'undefined') {
      env = value
      l = value.language
    }
  })

  async function submit() {
    splash = true
    ;(await apiAuth.getAuth(name + '', password + '')).subscribe({
      next: async (res) => {
        cookies.add({
          name: 'JWT',
          value: res.body?.data?.jwt + '',
          expireDays: 30,
        })
        goto('/dashboard')
      },
      error: (err) => {
        splash = false
      },
    })
  }

</script>

<svelte:head>
  <title>{l.auth.login} • {env.name} AdminTool</title>
</svelte:head>

<form on:submit|preventDefault={submit}>
  {#if splash}
    <LoadingSplash transparent={true} />
  {/if}

  <h2>{l.auth.login}</h2>
  <p>{env.name} AdminTool</p>
  <input type="text" placeholder={l.main.username} name="name" bind:value={name} />
  <input type="password" placeholder={l.main.password} name="password" bind:value={password} />
  <button class="primary">{l.auth.login}</button>
  <p class="center">
    <a class="small-link" href="/register">{l.auth.createAccount}</a>
  </p>
</form>
