// client/app/modals/language-modal/language-modal.component.ts
import { Component, Input, OnInit } from '@angular/core';
import en from 'client/app/shared/language/en';
import { LanguageService } from 'client/app/shared/services/language.service';

@Component({
  selector: 'app-language-modal',
  templateUrl: './language-modal.component.html',
  styleUrls: ['./language-modal.component.scss']
})
export class LanguageModalComponent implements OnInit {
  @Input() id: string = 'modal'

  l = en

  constructor(private languageService: LanguageService) {}

  async ngOnInit() {
    this.languageService.get().subscribe({ next: (l) => this.l = l })
  }
}

<app-modal-template [id]="id" [size]="'s'">
  <h2 [innerHTML]="l.modals.language.title | html"></h2>
  <p [innerHTML]="l.modals.language.content | html"></p>
  <div class="actions">
    <a class="not-a" href="https://github.com/Electron-Minecraft-Launcher/EML-AdminTool-v2" target="_blank"><button class="primary"><span [innerHTML]="l.main.more | html"></span>...&nbsp;&nbsp;<i class="fa-solid fa-arrow-up-right-from-square"></i></button></a>
  </div>
</app-modal-template>

// src/components/modals/LanguageModal.svelte
<script lang="ts">
  import ModalTemplate from './__ModalTemplate.svelte'
  import { l } from '$lib/stores/language'

  interface Props {
    show: boolean
  }

  let { show = $bindable() }: Props = $props()
</script>

<ModalTemplate size={'s'} bind:show>
  <h2>{@html $l.setup.step1.modals.language.title}</h2>
  <p>{@html $l.setup.step1.modals.language.content}</p>
  <div class="actions">
    <a class="not-a" href="https://github.com/Electron-Minecraft-Launcher/EML-AdminTool-v2?tab=readme-ov-file#want-to-help" target="_blank">
      <button class="primary">{@html $l.main.more}...&nbsp;&nbsp;<i class="fa-solid fa-arrow-up-right-from-square"></i></button>
    </a>
  </div>
</ModalTemplate>

<style lang="scss">
  @use '../../../static/scss/modals.scss';
</style>
