// client/app/manager/skeleton/skeleton.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-skeleton',
  templateUrl: './skeleton.component.html',
  styleUrls: ['./skeleton.component.scss']
})
export class SkeletonComponent implements OnInit {

  @Input() padding: string = '0px'
  @Input() height: string = '24px'
  @Input() randomWidth: { times: number, min: number } = { times: 100, min: 30 }
  @Input() customStyle: { [key: string]: string }[] = []
  width: string = ''
  style = ''

  ngOnInit() {

    this.width = (Math.random() * this.randomWidth.times + this.randomWidth.min) + 'px'

    this.style += 'padding: ' + this.padding + '; '
    this.style += 'height: ' + this.height + '; '
    this.style += 'width: ' + this.width + '; '

    this.customStyle.forEach(element => {
      this.style += Object.entries(element)[0][0] + ': ' + element[Object.entries(element)[0][0]] + ' !important; '
    })

  }

}

<span class="span-skeleton" [style]="style"></span>

// client/src/components/layouts/Skeleton.svelte
<script lang="ts">
  export let padding: string = '0px'
  export let height: string = '24px'
  export let randomWidth: { times: number, min: number } = { times: 100, min: 30 }
  export let customStyle: { [key: string]: string }[] = []
  let width: string = ''
  let style = ''

  width = (Math.random() * randomWidth.times + randomWidth.min) + 'px'

    style += 'padding: ' + padding + '; '
    style += 'height: ' + height + '; '
    style += 'width: ' + width + '; '

    customStyle.forEach(element => {
      style += Object.entries(element)[0][0] + ': ' + element[Object.entries(element)[0][0]] + ' !important; '
    })
</script>

<span class="span-skeleton" {style} />

<style lang="scss">
  span {
    display: inline-block;
    height: 24px;
    animation-name: skeleton;
    animation-duration: 1.3s;
    animation-timing-function: ease;
    animation-iteration-count: infinite;
    border-radius: 3px;
    min-width: 30px;
  }

  @keyframes skeleton {
    0% {
      background: #e5e5e5;
    }

    40% {
      background: #eaeaea;
    }

    60% {
      background: #e5e5e5;
    }

    100% {
      background: #e5e5e5;
    }
  }
</style>
