// client/app/home/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Router } from '@angular/router';
import { ApiAuthService } from 'client/app/shared/services/api/api-auth.service';
import { EnvService } from 'client/app/shared/services/env.service';
import { CookiesService } from 'client/app/shared/services/cookie.service';
import en from 'client/app/shared/language/en';
import { User } from 'client/app/shared/types/user';
import { UserService } from 'client/app/shared/services/user.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  l = en
  env: any
  user!: User

  constructor(private router: Router, private title: Title, private envService: EnvService, private userService: UserService, private apiAuthService: ApiAuthService, private cookiesService: CookiesService) { }

  async ngOnInit() {

    this.userService.get().subscribe({ next: (user) => this.user = user })
    this.envService.get().subscribe({ next: (env) => { this.l = env.language; this.env = env; } })

    this.title.setTitle(this.env.name + ' AdminTool')
  }

}

<app-left-panel></app-left-panel>

<div class="container">


  <h2>Home</h2>

  <app-skeleton [randomWidth]="{times: 100, min: 200}" *ngIf="!user"></app-skeleton>
  <h3 *ngIf="user">Welcome, {{ user.name }}!</h3>


</div>

// client/src/routes/dashboard/+page.svelte
<script lang="ts">
  import type en from '$assets/language/en'
  import type fr from '$assets/language/fr'
  import LeftPanel from '$components/LeftPanel.svelte'
  import Skeleton from '$components/Skeleton.svelte'
  import type { Env } from '$models/data/env.model'
  import type { User } from '$models/features/user.model'
  import { env$, user$ } from '$services/store'
  //   import type { PageData } from './$types'

  //   export let data: PageData

  let env!: Env
  let l: typeof en | typeof fr
  let user: User

  env$.subscribe((value) => {
    if (value && value.language && typeof value.language !== 'string') {
      env = value
      l = value.language
    }
  })

  user$.subscribe((value) => {
    if (value) {
      user = value
    }
  })
</script>

<svelte:head>
  <title>{env.name} AdminTool</title>
</svelte:head>

<LeftPanel />

<div class="container">
  <h2>Home</h2>

  {#if !user}
    <Skeleton randomWidth={{ times: 100, min: 200 }} />
  {:else}
    <h3>Welcome, {user.name}!</h3>
  {/if}
</div>

<style lang="scss">
  div.container {
    margin-left: 260px;
    padding: 30px 100px;
  }

  h2 {
    margin-top: 0;
    font-size: 32px;
  }
</style>
