// client/app/configuration/configuration-form-template/configuration-form-template.component.ts
import { HttpResponse } from '@angular/common/http';
import { Component, Input, OnInit, Output } from '@angular/core';
import { DefaultResponse } from 'client/app/shared/models/responses/response.model';
import { ApiConfigureService } from 'client/app/shared/services/api/api-configure.service';
import { StepManagerService } from 'client/app/shared/services/configure/step-manager.service';
import { EnvService } from 'client/app/shared/services/env.service';
import { UtilsService } from 'client/app/shared/services/utils.service';
import { Config } from 'client/app/shared/models/configurations/config.model';
import { User } from 'client/app/shared/models/features/user.model';
import { Observable } from 'rxjs';
import en from 'client/app/shared/language/en';

@Component({
  selector: 'app-configuration-form-template',
  templateUrl: './configuration-form-template.component.html',
  styleUrls: ['./configuration-form-template.component.scss']
})
export class ConfigurationFormTemplateComponent implements OnInit {

  l = en

  @Input() id!: string

  @Input() prev: boolean = true
  @Input() next: boolean = true
  @Input() cond: boolean = true
  @Input() language?: Config
  @Input() dbPassword?: string
  @Input() adminAccount?: User

  private putLanguage$!: Observable<HttpResponse<DefaultResponse>>
  private putDbPassword$!: Observable<HttpResponse<DefaultResponse>>
  step: 0 | 1 | 2 | 3 | 4 = 0

  constructor(private apiConfigureService: ApiConfigureService, private stepManagerService: StepManagerService, private utils: UtilsService, private envService: EnvService) {
    this.stepManagerService.getStep().subscribe((step) => {
      this.step = step
    })
  }

  ngOnInit() {
    this.envService.get().subscribe({ next: (env) => this.l = env.language })
  }

  async onSubmit() {
    if (this.language) {
      document.querySelector<HTMLElement>('app-loading-splash#config-1')!.style.display = 'block'
      this.putLanguage$ = this.apiConfigureService.putLanguage(this.language.value)
      this.putLanguage$.subscribe(
        {
          next: async (res) => {
            this.stepManagerService.updateStep(2)
            await this.utils.sleep(500)
            document.querySelector<HTMLElement>('app-loading-splash#config-1')!.style.display = 'none'
          }
        }
      )
    }
    if (this.dbPassword) {
      document.querySelector<HTMLElement>('app-loading-splash#config-2')!.style.display = 'block'
      this.putDbPassword$ = this.apiConfigureService.putDbPassword(this.dbPassword)
      this.putDbPassword$.subscribe(
        {
          next: async (res) => {
            this.stepManagerService.updateStep(3)
            await this.utils.sleep(500)
            document.querySelector<HTMLElement>('app-loading-splash#config-2')!.style.display = 'none'
          }
        }
      )
    }
    if (this.adminAccount) {
      document.querySelector<HTMLElement>('app-loading-splash#config-3')!.style.display = 'block'
      this.putDbPassword$ = this.apiConfigureService.putAdmin(this.adminAccount.name + '', this.adminAccount.password + '')
      this.putDbPassword$.subscribe(
        {
          next: async (res) => {
            this.stepManagerService.updateStep(4)
            await this.utils.sleep(500)
            document.querySelector<HTMLElement>('app-loading-splash#config-3')!.style.display = 'none'
          }
        }
      )
    }
  }

  onPrevious() {
    let step = this.step - 1
    if (step == 0 || step == 1 || step == 2 || step == 3 || step == 4) {
      this.stepManagerService.updateStep(step)
    }
  }

}

<form (ngSubmit)="onSubmit()">
  <app-loading-splash [transparent]="true" [id]="id"></app-loading-splash>
  <ng-content select="h2"></ng-content>
  <ng-content select="p"></ng-content>
  <ng-content select="div.actions"></ng-content>
  <div class="steps-actions">
    <div class="prev" *ngIf="prev" [ngStyle]="{'width': !next ? '100%' : ''}">
      <button type="button" class="secondary" (click)="onPrevious()"><i
          class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;<span [innerHTML]="l.main.prev | html"></span></button>
    </div>
    <div class="next" *ngIf="next" [ngStyle]="{'width': !prev ? '100%' : ''}">
      <button type="submit" class="primary" [disabled]="!cond"><span [innerHTML]="step < 3 ? l.main.next : l.main.finish | html"></span>&nbsp;&nbsp;<i
          class="fa-solid fa-arrow-right"></i></button>
    </div>
  </div>
</form>

// src/components/setup/ConfigurationFormTemplate.svelte
<script lang="ts">
  import { l } from '../../services/store'
  import LoadingSplash from '../layouts/LoadingSplash.svelte'
  import apiConfigureService from '../../services/api/api-configure.service'
  import { createEventDispatcher } from 'svelte'
  import utils from '../../services/utils'

  interface Props {
    step: number
    cond?: boolean
    prev?: boolean
    next?: boolean
    nextStep: (arg: { step: number }) => void
    prevStep?: (arg: { step: number }) => void
    data: { data: 'LANGUAGE' | 'DATABASE' | 'ADMIN'; value: any }
    children?: import('svelte').Snippet
  }

  let { step, cond = true, prev = true, next = true, nextStep, prevStep, data, children }: Props = $props()

  let splash = $state(false)

  async function submit(e: SubmitEvent) {
    e.preventDefault()
    if (data.data == 'LANGUAGE') {
      splash = true
      ;(await apiConfigureService.putLanguage(data.value)).subscribe({
        next: async (res) => {
          nextStep({ step: step + 1 })
          await utils.sleep(500)
          splash = false
        }
      })
    }
    if (data.data == 'DATABASE') {
      splash = true
      ;(await apiConfigureService.putDbPassword(data.value)).subscribe({
        next: async (res) => {
          nextStep({ step: step + 1 })
          await utils.sleep(500)
          splash = false
        }
      })
    }
    if (data.data == 'ADMIN') {
      splash = true
      ;(await apiConfigureService.putAdmin(data.value.name + '', data.value.password + '')).subscribe({
        next: async (res) => {
          nextStep({ step: step + 1 })
          await utils.sleep(500)
          splash = false
        }
      })
    }
  }
</script>

<form onsubmit={submit}>
  {#if splash}
    <LoadingSplash transparent={true} />
  {/if}
  {@render children?.()}
  <div class="steps-actions">
    {#if prev}
      <div class="prev" style={'width: ' + (!next ? '100%' : 'auto')}>
        <button
          type="button"
          class="secondary"
          onclick={() => {
            if (prevStep) prevStep({ step: step - 1 })
          }}
        >
          <i class="fa-solid fa-arrow-left"></i>&nbsp;&nbsp;<span>{$l.main.prev}</span>
        </button>
      </div>
    {/if}
    {#if next}
      <div class="next" style={!prev ? 'width: 100%' : 'float: right; position: relative; top: -5px'}>
        <button type="submit" class="primary" disabled={!cond}>
          <span>{step < 3 ? $l.main.next : $l.main.finish}</span>&nbsp;&nbsp;<i class="fa-solid fa-arrow-right"></i>
        </button>
      </div>
    {/if}
  </div>
</form>

<style lang="scss">
  @use '../../assets/scss/configure.scss';
</style>
