// client/src/routes/(unauthed)/login/+page.svelte
<script lang="ts">
  import LoadingSplash from '../../../components/layouts/LoadingSplash.svelte'
  import { env$, user$ } from '../../../services/store'
  import apiAuthService from '../../../services/api/api-auth.service'
  import cookiesService from '../../../services/cookies.service'
  import type { Env } from '../../../../../shared/models/data/env.model'
  import type en from '../../../assets/language/en'
  import { goto } from '$app/navigation'
  import type fr from '../../../assets/language/fr'

  let env!: Env
  let l: typeof en | typeof fr

  env$.subscribe((value) => {
    env = value
    l = value.language
  })

  let name: string = ''
  let password = ''
  let splash: boolean = false

  async function submit() {
    splash = true
    ;(await apiAuthService.getAuth(name + '', password + '')).subscribe({
      next: async (res) => {
        cookiesService.add({
          name: 'JWT',
          value: res.body?.data?.jwt + '',
          expireDays: 30
        })
        user$.set(res.body?.data?.user!)
        goto('/dashboard')
      },
      error: () => {
        splash = false
      }
    })
  }
</script>

<svelte:head>
  <title>{l.auth.login} • {env.name} AdminTool</title>
</svelte:head>

<form on:submit|preventDefault={submit}>
  {#if splash}
    <LoadingSplash transparent={true} />
  {/if}

  <h2>{l.auth.login}</h2>
  <p>{env.name} AdminTool</p>

  <label for="name">{l.main.username}</label>
  <input type="text" id="name" placeholder={l.main.username} bind:value={name} />

  <label for="username">{l.main.password}</label>
  <input type="password" id="username" placeholder={l.main.password} bind:value={password} />

  <button class="primary">{l.auth.login}</button>
  <p class="center">
    <a class="small-link" href="/register">{l.auth.createAccount}</a>
  </p>
</form>

<style lang="scss">
  @import '../../../assets/scss/login.scss';
</style>

// client/app/home/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Router } from '@angular/router';
import { EnvService } from 'client/app/shared/services/env.service';
import en from 'client/app/shared/language/en';
import { ApiAuthService } from 'client/app/shared/services/api/api-auth.service';
import { CookiesService } from 'client/app/shared/services/cookie.service';
import { HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { DataResponse } from 'client/app/shared/types/response';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  l = en
  env: any

  name: string = ''
  password: string = ''

  private getAuth$!: Observable<HttpResponse<DataResponse<{ jwt: string }>>>

  constructor(private router: Router, private title: Title, private envService: EnvService, private apiAuthService: ApiAuthService, private cookiesService: CookiesService) { }

  async ngOnInit() {

    this.envService.get().subscribe({ next: (env) => { this.l = env.language; this.env = env; } })

    this.title.setTitle(this.l.auth.login + ' • ' + this.env.name + ' AdminTool')

    if (this.cookiesService.getCookie('JWT')) {
      this.apiAuthService.getVerify().subscribe({
        next: (res) => {
          this.router.navigate(['/dashboard'])
        }
      })
    }

  }

  async onSubmit() {

    document.querySelector<HTMLElement>('app-loading-splash#login-loading-splash')!.style.display = 'block'
    this.getAuth$ = this.apiAuthService.getAuth(this.name + '', this.password + '')
    this.getAuth$.subscribe(
      {
        next: async (res) => {
          this.cookiesService.setCookie({
            name: 'JWT',
            value: res.body?.data?.jwt + '',
            expireDays: 30,
          })
          this.router.navigate(['/dashboard'])
        },
        error: (err) => {
          document.querySelector<HTMLElement>('app-loading-splash#login-loading-splash')!.style.display = 'none'
        }
      }
    )

  }

}

<form (ngSubmit)="onSubmit()">
  <app-loading-splash [transparent]="true" id="login-loading-splash"></app-loading-splash>
  <h2 [innerHTML]="l.auth.login | html"></h2>
  <p>{{ env.name }} AdminTool</p>
  <input type="text" [placeholder]="l.main.username" [(ngModel)]="name" name="name">
  <input type="password" [placeholder]="l.main.password" [(ngModel)]="password" name="password">
  <button class="primary" [innerHTML]="l.auth.login| html"></button>
  <p class="center">
    <a class="small-link" routerLink="/register" [innerHTML]="l.auth.createAccount | html"></a>
  </p>
</form>
