// client/app/home/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import { Router } from '@angular/router';
import { EnvService } from 'client/app/shared/services/env.service';
import en from 'client/app/shared/language/en';
import { Observable } from 'rxjs';
import { HttpResponse } from '@angular/common/http';
import { DataResponse } from 'client/app/shared/types/response';
import { ApiAuthService } from 'client/app/shared/services/api/api-auth.service';
import { CookiesService } from 'client/app/shared/services/cookie.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  l = en
  env: any

  name: string = ''
  password: string = ''
  passwordCfr: string = ''
  pin: string[] = ['', '', '']

  private putRegister$!: Observable<HttpResponse<DataResponse<{ jwt: string }>>>

  constructor(private router: Router, private title: Title, private envService: EnvService, private apiAuthService: ApiAuthService, private cookiesService: CookiesService) { }

  async ngOnInit() {

    this.envService.get().subscribe({ next: (env) => { this.l = env.language; this.env = env; } })

    this.title.setTitle(this.l.auth.register + ' • ' + this.env.name + ' AdminTool')

  }

  focusNext(e: KeyboardEvent, n: number) {
    var input = document.querySelector<HTMLInputElement>('input#pin-' + n)!
    const i = e.target! as HTMLInputElement
    if (!/^[0-9]+$/.test(input.value) && input.value != '') {
      input.value = ''
      return
    }
    if (input.value.length == 1) {
      var nextInput = document.querySelector<HTMLInputElement>('input#pin-' + (n + 1))
      if (nextInput) {
        nextInput.focus()
      }
      return
    }
    if (e.keyCode == 8 || e.keyCode == 46) {
      if (i.value == '') {
        var previousInput = document.querySelector<HTMLInputElement>('input#pin-' + (n - 1))
        if (previousInput) {
          previousInput.focus()
        }
      }
      return
    }
  }

  async onSubmit() {

    document.querySelector<HTMLElement>('app-loading-splash#register-loading-splash')!.style.display = 'block'
    this.putRegister$ = this.apiAuthService.putRegister(this.name + '', this.password + '', this.pin[0] + '' + this.pin[1] + '' + this.pin[2])
    this.putRegister$.subscribe(
      {
        next: async (res) => {
          this.cookiesService.setCookie({
            name: 'JWT',
            value: res.body?.data?.jwt + '',
            expireDays: 30,
          })
        },
        error: (err) => {
          document.querySelector<HTMLElement>('app-loading-splash#register-loading-splash')!.style.display = 'none'
        }
      }
    )

  }

}


<form (ngSubmit)="onSubmit()">
  <app-loading-splash [transparent]="true" id="register-loading-splash"></app-loading-splash>
  <h2 [innerHTML]="l.auth.register | html"></h2>
  <p>{{ env.name }} AdminTool</p>
  <input type="text" [placeholder]="l.main.username" [(ngModel)]="name" name="name">
  <input type="password" [placeholder]="l.main.password" [(ngModel)]="password" name="password">
  <input type="password" [placeholder]="l.auth.confirmPassword" [(ngModel)]="passwordCfr" name="password-cfr">
  <label for="pin-1" [innerHTML]="l.main.pin + (l.l == 'fr' ? ' :&nbsp;&nbsp;' : ':&nbsp;&nbsp')"></label>
  <input type="text" maxlength="1" size="1" id="pin-1" (keyup)="focusNext($event, 1)" [(ngModel)]="pin[0]" name="pin-1">
  <input type="text" maxlength="1" size="1" id="pin-2" (keyup)="focusNext($event, 2)" [(ngModel)]="pin[1]" name="pin-2">
  <input type="text" maxlength="1" size="1" id="pin-3" (keyup)="focusNext($event, 3)" [(ngModel)]="pin[2]" name="pin-3">

  <button class="primary" [innerHTML]="l.auth.register | html"
    [disabled]="!name || !password || password != passwordCfr || !pin[0] || !pin[1] || !pin[2]"></button>
  <p class="center">
    <a class="small-link" routerLink="/login" [innerHTML]="l.auth.alreadyAnAccount | html"></a>
  </p>
</form>

// src/routes/(app)/register/+page.svelte
<script lang="ts">
  import { l } from '$lib/stores/language'
  import LoadingSplash from '../../../components/layouts/LoadingSplash.svelte'
  import type { PageProps } from './$types'
  import getEnv from '$lib/utils/env'
  import Footer from '../../../components/layouts/Footer.svelte'

  let { data }: PageProps = $props()

  const env = getEnv()

  let showLoader = $state(false)

  let username = $state('')
  let password = $state('')
  let passwordCfr = $state('')
  let pin = $state(['', '', ''])

  function focusNext(e: KeyboardEvent) {
    const input = e.target as HTMLInputElement
    const n = +input.id.split('-')[1]

    if (!/^[0-9]+$/.test(input.value) && input.value != '') {
      input.value = ''
      return
    }
    if (input.value.length == 1) {
      var nextInput = document.querySelector<HTMLInputElement>('input#pin-' + (n + 1))
      if (nextInput) {
        nextInput.focus()
      }
      return
    }
    if (e.keyCode == 8 || e.keyCode == 46) {
      if (input.value == '') {
        var previousInput = document.querySelector<HTMLInputElement>('input#pin-' + (n - 1))
        if (previousInput) {
          previousInput.focus()
        }
      }
      return
    }
  }
</script>

<svelte:head>
  <title>{$l.auth.register} • {env.name} AdminTool</title>
</svelte:head>

<form>
  {#if showLoader}
    <LoadingSplash transparent={true} />
  {/if}

  <h2>{$l.auth.register}</h2>
  <p>{env.name} AdminTool</p>

  <label for="name">{$l.main.username}</label>
  <input type="text" id="name" bind:value={username} />

  <label for="password">{$l.main.password}</label>
  <input type="password" id="password" bind:value={password} />

  <label for="password-cfr">{$l.auth.confirmPassword}</label>
  <input type="password" id="password-cfr" bind:value={passwordCfr} />

  <div class="pin-inputs">
    <label for="pin-1" style="display: inline-block">{@html $l.main.pin + ($l.l == 'fr' ? ' :&nbsp;&nbsp;' : ':&nbsp;&nbsp')}</label>
    <input type="text" maxlength="1" size="1" id="pin-1" onkeyup={focusNext} bind:value={pin[0]} />
    <input type="text" maxlength="1" size="1" id="pin-2" onkeyup={focusNext} bind:value={pin[1]} />
    <input type="text" maxlength="1" size="1" id="pin-3" onkeyup={focusNext} bind:value={pin[2]} />
  </div>

  <button class="primary" disabled={!username || !password || password != passwordCfr || !pin[0] || !pin[1] || !pin[2]}>
    {$l.auth.register}
  </button>
  <p class="center">
    <a class="small-link" href="/login">{$l.auth.alreadyAnAccount}</a>
  </p>
</form>

<style lang="scss">
  @use '../../../../assets/scss/login.scss';

  div.pin-inputs {
    display: flex;
    align-items: center;
    margin-top: 20px;

    label {
      margin-right: 0.5rem;
      margin-bottom: 0;
    }

    input {
      margin-top: 0 !important;
    }
  }
</style>
